# Домашнее задание к уроку 1: Основы PyTorch

# Задание 1: Создание и манипуляции с тензорами (25 баллов)

In [ ]:
import torch

In [ ]:
# Создайте следующие тензоры:
# - Тензор размером 3x4, заполненный случайными числами от 0 до 1
tensor1 = torch.rand(3,4)
tensor1

tensor([[0.0603, 0.6727, 0.7556, 0.9811],
        [0.9981, 0.1168, 0.5711, 0.0989],
        [0.5028, 0.9625, 0.4597, 0.2585]])

In [ ]:
# - Тензор размером 2x3x4, заполненный нулями
tensor2 = torch.zeros((2,3,4))
tensor2

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
# - Тензор размером 5x5, заполненный единицами
tensor3 = torch.ones((5,5))
tensor3

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [ ]:
# - Тензор размером 4x4 с числами от 0 до 15 (используйте reshape)
tensor4 = torch.arange(16).reshape(4, 4)
tensor4

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

# 1.2 Операции с тензорами (6 баллов)

In [ ]:
# Дано: тензор A размером 3x4 и тензор B размером 4x3
a = torch.rand(3,4)
b = torch.rand(4,3)

In [ ]:
# Выполните:
# - Транспонирование тензора A
a.T

tensor([[0.0300, 0.7507, 0.6765],
        [0.8243, 0.3682, 0.3869],
        [0.4591, 0.3527, 0.8975],
        [0.9222, 0.6280, 0.1192]])

In [ ]:
# - Матричное умножение A и B
a @ b

tensor([[1.4543, 0.6996, 1.7359],
        [1.0897, 0.6349, 1.3197],
        [1.3230, 0.3458, 1.2059]])

In [ ]:
# - Поэлементное умножение A и транспонированного B
a * b.T

tensor([[0.0069, 0.4605, 0.4512, 0.5357],
        [0.2050, 0.0793, 0.0048, 0.3458],
        [0.2874, 0.3856, 0.4459, 0.0870]])

In [ ]:
# - Вычислите сумму всех элементов тензора A
a.sum()

tensor(6.4152)

# 1.3 Индексация и срезы (6 баллов)

In [ ]:
# Создайте тензор размером 5x5x5
tensor = torch.rand(5,5,5)
tensor

tensor([[[0.8545, 0.5801, 0.2011, 0.8761, 0.1190],
         [0.6861, 0.6458, 0.0376, 0.8708, 0.8126],
         [0.4541, 0.3553, 0.2051, 0.6067, 0.6136],
         [0.5420, 0.8055, 0.9934, 0.0019, 0.4882],
         [0.5666, 0.6688, 0.0947, 0.5199, 0.0301]],

        [[0.5252, 0.8803, 0.0326, 0.5650, 0.1351],
         [0.8140, 0.6607, 0.2103, 0.8511, 0.8263],
         [0.9790, 0.0402, 0.0666, 0.4459, 0.9108],
         [0.8751, 0.5392, 0.5700, 0.6048, 0.9933],
         [0.6660, 0.1736, 0.4736, 0.3615, 0.5890]],

        [[0.0129, 0.0858, 0.5996, 0.0209, 0.7184],
         [0.6941, 0.0329, 0.3695, 0.6023, 0.7235],
         [0.0087, 0.7752, 0.5535, 0.3891, 0.7901],
         [0.1825, 0.1272, 0.5219, 0.7960, 0.5182],
         [0.0753, 0.6088, 0.9244, 0.0168, 0.3007]],

        [[0.0525, 0.0397, 0.1657, 0.8015, 0.7749],
         [0.9708, 0.3814, 0.1653, 0.7982, 0.7007],
         [0.3103, 0.3488, 0.1005, 0.2809, 0.0433],
         [0.9459, 0.1665, 0.1233, 0.0701, 0.7112],
         [0.7157, 0.5961,

In [ ]:
# Извлеките:
# - Первую строку
tensor[0, 0, :]

tensor([0.8545, 0.5801, 0.2011, 0.8761, 0.1190])

In [ ]:
# - Последний столбец
tensor[:, :, -1]

tensor([[0.1190, 0.8126, 0.6136, 0.4882, 0.0301],
        [0.1351, 0.8263, 0.9108, 0.9933, 0.5890],
        [0.7184, 0.7235, 0.7901, 0.5182, 0.3007],
        [0.7749, 0.7007, 0.0433, 0.7112, 0.1823],
        [0.4190, 0.7458, 0.4917, 0.0175, 0.6850]])

In [ ]:
# - Подматрицу размером 2x2 из центра тензора
tensor[2:4, 2:4, 2:4]

tensor([[[0.5535, 0.3891],
         [0.5219, 0.7960]],

        [[0.1005, 0.2809],
         [0.1233, 0.0701]]])

In [ ]:
# - Все элементы с четными индексами
tensor[::2, ::2, ::2]

tensor([[[0.8545, 0.2011, 0.1190],
         [0.4541, 0.2051, 0.6136],
         [0.5666, 0.0947, 0.0301]],

        [[0.0129, 0.5996, 0.7184],
         [0.0087, 0.5535, 0.7901],
         [0.0753, 0.9244, 0.3007]],

        [[0.6840, 0.7045, 0.4190],
         [0.3280, 0.5561, 0.4917],
         [0.9479, 0.5469, 0.6850]]])

# 1.4 Работа с формами (6 баллов)

In [ ]:
# Создайте тензор размером 24 элемента
tensor1_4 = torch.rand(24)
tensor1_4

tensor([0.2149, 0.5922, 0.3224, 0.2979, 0.8415, 0.9189, 0.6091, 0.7184, 0.5326,
        0.1561, 0.0269, 0.9625, 0.1213, 0.0290, 0.1337, 0.6695, 0.2124, 0.5930,
        0.9885, 0.1040, 0.8561, 0.6550, 0.8175, 0.5196])

In [ ]:
# Преобразуйте его в формы:
# - 2x12
tensor1_4.view(2, 12)

tensor([[0.2149, 0.5922, 0.3224, 0.2979, 0.8415, 0.9189, 0.6091, 0.7184, 0.5326,
         0.1561, 0.0269, 0.9625],
        [0.1213, 0.0290, 0.1337, 0.6695, 0.2124, 0.5930, 0.9885, 0.1040, 0.8561,
         0.6550, 0.8175, 0.5196]])

In [ ]:
# - 3x8
tensor1_4.view(3, 8)

In [ ]:

# - 4x6
tensor1_4.view(4, 6)

tensor([[0.2149, 0.5922, 0.3224, 0.2979, 0.8415, 0.9189],
        [0.6091, 0.7184, 0.5326, 0.1561, 0.0269, 0.9625],
        [0.1213, 0.0290, 0.1337, 0.6695, 0.2124, 0.5930],
        [0.9885, 0.1040, 0.8561, 0.6550, 0.8175, 0.5196]])

In [ ]:
# - 2x3x4
tensor1_4.view(2, 3, 4)

tensor([[[0.2149, 0.5922, 0.3224, 0.2979],
         [0.8415, 0.9189, 0.6091, 0.7184],
         [0.5326, 0.1561, 0.0269, 0.9625]],

        [[0.1213, 0.0290, 0.1337, 0.6695],
         [0.2124, 0.5930, 0.9885, 0.1040],
         [0.8561, 0.6550, 0.8175, 0.5196]]])

In [ ]:
# - 2x2x2x3
tensor1_4.view(2, 2, 2, 3)

tensor([[[[0.2149, 0.5922, 0.3224],
          [0.2979, 0.8415, 0.9189]],

         [[0.6091, 0.7184, 0.5326],
          [0.1561, 0.0269, 0.9625]]],


        [[[0.1213, 0.0290, 0.1337],
          [0.6695, 0.2124, 0.5930]],

         [[0.9885, 0.1040, 0.8561],
          [0.6550, 0.8175, 0.5196]]]])

# Задание 2: Автоматическое дифференцирование (25 баллов)

**2.1 Простые вычисления с градиентами (8 баллов)**

In [ ]:
# Создайте тензоры x, y, z с requires_grad=True
x = torch.tensor(1.0, requires_grad=True)
y = torch.tensor(2.0, requires_grad=True)
z = torch.tensor(3.0, requires_grad=True)

In [ ]:
# Вычислите функцию: f(x,y,z) = x^2 + y^2 + z^2 + 2*x*y*z
f = x**2 + y**2 + z**2 + 2*x*y*z
f.backward()

In [ ]:
# Найдите градиенты по всем переменным
print(f"df/dx={x.grad.item()}, df/dy={y.grad.item()}, df/dz={z.grad.item()}")

df/dx=14.0, df/dy=10.0, df/dz=10.0


In [ ]:
# Проверьте результат аналитически
# df/dx = 2x + 2yz = 14, df/dy=2y+2xz = 10, df/dz=2z+2xy = 10

**2.2 Градиент функции потерь (9 баллов)**

In [31]:
# Реализуйте функцию MSE (Mean Squared Error):
# MSE = (1/n) * Σ(y_pred - y_true)^2
def mse(y_pred, y_true):
    return torch.mean((y_pred - y_true) ** 2)

x_data = torch.randn(10, requires_grad=False)
x_data

tensor([ 0.2337,  2.7257, -0.8477, -2.0133,  0.3288,  0.5381, -0.6941,  0.9533,
         0.0850, -0.8341])

In [34]:
y_true = 3 + 3*x_data + torch.randn(10) * 0.1
y_true

tensor([ 3.6853, 11.3580,  0.6047, -3.0414,  3.9919,  4.5407,  0.7613,  5.7988,
         3.3473,  0.5177])

In [35]:
w = torch.tensor(0.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

# где y_pred = w * x + b (линейная функция)
y_pred = w * x_data + b
loss = mse(y_pred, y_true)
loss.backward()

In [36]:
# Найдите градиенты по w и b
print(f"dMSE/dw={w.grad.item()}, dMSE/db={b.grad.item()}")

dMSE/dw=-9.207743644714355, dMSE/db=-6.312876224517822


**2.3 Цепное правило (8 баллов)**

In [37]:
# Реализуйте составную функцию: f(x) = sin(x^2 + 1)
x_var = torch.tensor(1.0, requires_grad=True)
f = torch.sin(x_var ** 2 + 1)
f.backward()

In [38]:
# Найдите градиент df/dx
print("Градиент;", x_var.grad.item())

Градиент; -0.832293689250946


In [39]:
# Проверьте результат с помощью torch.autograd.grad
grad = torch.autograd.grad(torch.sin(x_var ** 2 + 1), x_var)[0]
print("Проверка:", grad.item())

Проверка: -0.832293689250946


# Задание 3: Сравнение производительности CPU vs CUDA (20 баллов)

**3.1 Подготовка данных (5 баллов)**

In [1]:
import time
import torch
device_cpu = torch.device("cpu")
device_gpu = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [2]:
# Создайте большие матрицы размеров:
# - 64 x 1024 x 1024
# - 128 x 512 x 512
# - 256 x 256 x 256
# Заполните их случайными числами
sizes = [(64, 1024, 1024), (128, 512, 512), (256, 256, 256)]
tensors = [torch.randn(*size) for size in sizes]

**3.2 Функция измерения времени (5 баллов)**

In [10]:
# Создайте функцию для измерения времени выполнения операций
def compute_time(op, x_cpu, x_gpu):
    # CPU
    # Используйте time.time() для измерения на CPU
    start_cpu = time.time()
    op(x_cpu)
    cpu_time = (time.time() - start_cpu) * 1000  # в мс

    # GPU
    # Используйте torch.cuda.Event() для точного измерения на GPU
    if torch.cuda.is_available():
        start_event = torch.cuda.Event(enable_timing=True)
        end_event = torch.cuda.Event(enable_timing=True)

        start_event.record()
        op(x_gpu)
        end_event.record()
        torch.cuda.synchronize()
        gpu_time = start_event.elapsed_time(end_event)  # в мс
    else:
        gpu_time = None

    return cpu_time, gpu_time

**3.3 Сравнение операций (10 баллов)**

In [9]:
# Переносим на GPU
tensors_gpu = [x.cuda() for x in tensors]

results = []

# Для каждой матрицы выполним все операции
for i, (x_cpu, x_gpu) in enumerate(zip(tensors, tensors_gpu)):
    print(f"\nМатрица #{i+1} размер {x_cpu.shape}")

    # - Матричное умножение (torch.matmul)
    cpu_time, gpu_time = compute_time(lambda x: torch.matmul(x, x.transpose(-1, -2)), x_cpu, x_gpu)
    results.append((f"Мат. умножение [{i+1}]", cpu_time, gpu_time, cpu_time / gpu_time))

    # - Поэлементное сложение
    cpu_time, gpu_time = compute_time(lambda x: x + x, x_cpu, x_gpu)
    results.append((f"Поэлементное сложение [{i+1}]", cpu_time, gpu_time, cpu_time / gpu_time))

    # - Поэлементное умножение
    cpu_time, gpu_time = compute_time(lambda x: x * x, x_cpu, x_gpu)
    results.append((f"Поэлементное умножение [{i+1}]", cpu_time, gpu_time, cpu_time / gpu_time))

    # - Транспонирование
    cpu_time, gpu_time = compute_time(lambda x: x.transpose(-1, -2), x_cpu, x_gpu)
    results.append((f"Транспонирование [{i+1}]", cpu_time, gpu_time, cpu_time / gpu_time))

    # - Вычисление суммы всех элементов
    cpu_time, gpu_time = compute_time(lambda x: x.sum(), x_cpu, x_gpu)
    results.append((f"Сумма элементов [{i+1}]", cpu_time, gpu_time, cpu_time / gpu_time))

print(f"\n{'Операция':<35} {'CPU время (мс)':<15} {'GPU время (мс)':<15} {'Ускорение':<10}")
print("-" * 80)
for name, cpu, gpu, speedup in results:
    print(f"{name:<35} {cpu:<15.3f} {gpu:<15.3f} {speedup:<10.2f}")


Матрица #1 размер torch.Size([64, 1024, 1024])

Матрица #2 размер torch.Size([128, 512, 512])

Матрица #3 размер torch.Size([256, 256, 256])

Операция                            CPU время (мс)  GPU время (мс)  Ускорение 
--------------------------------------------------------------------------------
Мат. умножение [1]                  1193.489        51.067          23.37     
Поэлементное сложение [1]           143.125         2.282           62.71     
Поэлементное умножение [1]          139.365         2.289           60.89     
Транспонирование [1]                0.031           0.018           1.71      
Сумма элементов [1]                 21.926          1.110           19.75     
Мат. умножение [2]                  345.499         13.166          26.24     
Поэлементное сложение [2]           72.755          1.188           61.24     
Поэлементное умножение [2]          75.187          1.181           63.68     
Транспонирование [2]                0.029           0.016        

**3.4 Анализ результатов (5 баллов)**


**Какие операции получают наибольшее ускорение на GPU?**
Поэлементное сложение, умножение и матричное умножение (ускорение до ~80x).

GPU особенно эффективен для больших массивов и массовых операций.

**Почему некоторые операции могут быть медленнее на GPU?**
Транспонирование и сумма — очень лёгкие операции. Накладные расходы CUDA больше, чем время самой операции.

На малых или простых задачах GPU почти не даёт выигрыша.

**Как размер матриц влияет на ускорение?**
Чем больше размер, тем больше ускорение: крупные данные лучше загружают GPU.

Для максимальной выгоды GPU нужно использовать для больших массивов.

**Что происходит при передаче данных между CPU и GPU?**
Передача данных даёт значительные задержки и может ухудшить ускорение.

Данные надо загружать на GPU заранее и считать всё там.