# Домашнее задание к уроку 1: Основы PyTorch

# Задание 1: Создание и манипуляции с тензорами (25 баллов)

In [2]:
import torch

In [32]:
# Создайте следующие тензоры:
# - Тензор размером 3x4, заполненный случайными числами от 0 до 1
tensor1 = torch.rand(3,4)
tensor1

tensor([[0.8885, 0.5598, 0.1274, 0.6984],
        [0.4053, 0.1612, 0.5739, 0.9191],
        [0.8390, 0.5475, 0.5889, 0.2176]])

In [33]:
# - Тензор размером 2x3x4, заполненный нулями
tensor2 = torch.zeros((2,3,4))
tensor2

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [35]:
# - Тензор размером 5x5, заполненный единицами
tensor3 = torch.ones((5,5))
tensor3

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [36]:
# - Тензор размером 4x4 с числами от 0 до 15 (используйте reshape)
tensor4 = torch.arange(16).reshape(4, 4)
tensor4

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

# 1.2 Операции с тензорами (6 баллов)

In [ ]:
# Дано: тензор A размером 3x4 и тензор B размером 4x3
a = torch.rand(3,4)
b = torch.rand(4,3)

In [46]:
# Выполните:
# - Транспонирование тензора A
a.T

tensor([[0.0589, 0.2158, 0.7554],
        [0.3367, 0.7240, 0.4645],
        [0.3187, 0.4359, 0.4332],
        [0.2300, 0.6927, 0.9136]])

In [47]:
# - Матричное умножение A и B
a @ b

tensor([[0.5589, 0.4451, 0.5552],
        [1.2931, 1.0284, 1.1145],
        [1.8321, 1.3797, 1.3796]])

In [49]:
# - Поэлементное умножение A и транспонированного B
a * b.T

tensor([[0.0428, 0.0838, 0.2104, 0.2219],
        [0.1361, 0.3208, 0.1730, 0.3985],
        [0.4494, 0.2405, 0.3557, 0.3341]])

In [50]:
# - Вычислите сумму всех элементов тензора A
a.sum()

tensor(5.5794)

# 1.3 Индексация и срезы (6 баллов)

In [69]:
# Создайте тензор размером 5x5x5
tensor = torch.rand(5,5,5)
tensor
# - Подматрицу размером 2x2 из центра тензора
# - Все элементы с четными индексами

tensor([[[0.6576, 0.4046, 0.9137, 0.4757, 0.2412],
         [0.6289, 0.6264, 0.9892, 0.2655, 0.4826],
         [0.0853, 0.1963, 0.4745, 0.7093, 0.0086],
         [0.9664, 0.3230, 0.3542, 0.7225, 0.5433],
         [0.8065, 0.4410, 0.6551, 0.1614, 0.8334]],

        [[0.7354, 0.9364, 0.2039, 0.1353, 0.5935],
         [0.3625, 0.1174, 0.4672, 0.4447, 0.5871],
         [0.3647, 0.3909, 0.8328, 0.6034, 0.3470],
         [0.0545, 0.9567, 0.1506, 0.7007, 0.4806],
         [0.0060, 0.8387, 0.9125, 0.0851, 0.2819]],

        [[0.4771, 0.7416, 0.3028, 0.5266, 0.6874],
         [0.3634, 0.6198, 0.3185, 0.3624, 0.0723],
         [0.6787, 0.5110, 0.4343, 0.0182, 0.1209],
         [0.1437, 0.0931, 0.7490, 0.5429, 0.8072],
         [0.6447, 0.5566, 0.8224, 0.2788, 0.7021]],

        [[0.3059, 0.0764, 0.2327, 0.3448, 0.7248],
         [0.5960, 0.9729, 0.6472, 0.9384, 0.3966],
         [0.3313, 0.7814, 0.9063, 0.6307, 0.0010],
         [0.8149, 0.5870, 0.1070, 0.3753, 0.9714],
         [0.5692, 0.3041,

In [70]:
# Извлеките:
# - Первую строку
tensor[0, 0, :]

tensor([0.6576, 0.4046, 0.9137, 0.4757, 0.2412])

In [71]:
# - Последний столбец
tensor[:, :, -1]

tensor([[0.2412, 0.4826, 0.0086, 0.5433, 0.8334],
        [0.5935, 0.5871, 0.3470, 0.4806, 0.2819],
        [0.6874, 0.0723, 0.1209, 0.8072, 0.7021],
        [0.7248, 0.3966, 0.0010, 0.9714, 0.7309],
        [0.2057, 0.3550, 0.4285, 0.5935, 0.5486]])